In [1]:
import numpy as np 
import pandas as pd 
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

**2. Ensembles de données de laboratoire :**

*Question 1 :  
Téléchargez l'ensemble de données et affichez-en une partie.*

In [3]:
from sklearn.datasets import load_iris
iris_data = load_iris()
print("Partie des données Iris :")
print(iris_data.data[:5])

Partie des données Iris :
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


*Question 2: Écrire les données au format CSV.*

In [4]:
import pandas as pd
from io import StringIO

iris_df = pd.DataFrame(iris_data.data, columns=iris_data.feature_names)
csv_data = StringIO()
iris_df.to_csv(csv_data, index=False)
print("Données Iris au format CSV :")
print(csv_data.getvalue())

Données Iris au format CSV :
sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
5.1,3.5,1.4,0.2
4.9,3.0,1.4,0.2
4.7,3.2,1.3,0.2
4.6,3.1,1.5,0.2
5.0,3.6,1.4,0.2
5.4,3.9,1.7,0.4
4.6,3.4,1.4,0.3
5.0,3.4,1.5,0.2
4.4,2.9,1.4,0.2
4.9,3.1,1.5,0.1
5.4,3.7,1.5,0.2
4.8,3.4,1.6,0.2
4.8,3.0,1.4,0.1
4.3,3.0,1.1,0.1
5.8,4.0,1.2,0.2
5.7,4.4,1.5,0.4
5.4,3.9,1.3,0.4
5.1,3.5,1.4,0.3
5.7,3.8,1.7,0.3
5.1,3.8,1.5,0.3
5.4,3.4,1.7,0.2
5.1,3.7,1.5,0.4
4.6,3.6,1.0,0.2
5.1,3.3,1.7,0.5
4.8,3.4,1.9,0.2
5.0,3.0,1.6,0.2
5.0,3.4,1.6,0.4
5.2,3.5,1.5,0.2
5.2,3.4,1.4,0.2
4.7,3.2,1.6,0.2
4.8,3.1,1.6,0.2
5.4,3.4,1.5,0.4
5.2,4.1,1.5,0.1
5.5,4.2,1.4,0.2
4.9,3.1,1.5,0.2
5.0,3.2,1.2,0.2
5.5,3.5,1.3,0.2
4.9,3.6,1.4,0.1
4.4,3.0,1.3,0.2
5.1,3.4,1.5,0.2
5.0,3.5,1.3,0.3
4.5,2.3,1.3,0.3
4.4,3.2,1.3,0.2
5.0,3.5,1.6,0.6
5.1,3.8,1.9,0.4
4.8,3.0,1.4,0.3
5.1,3.8,1.6,0.2
4.6,3.2,1.4,0.2
5.3,3.7,1.5,0.2
5.0,3.3,1.4,0.2
7.0,3.2,4.7,1.4
6.4,3.2,4.5,1.5
6.9,3.1,4.9,1.5
5.5,2.3,4.0,1.3
6.5,2.8,4.6,1.5
5.7,2.8,4.5,1.3
6.3,3

*Question 3: Écrire les données au format JSON.*

In [8]:
import json
json_data = iris_df.to_json(orient="records")
print("Données Iris au format JSON :")
print(json_data)

Données Iris au format JSON :
[{"sepal length (cm)":5.1,"sepal width (cm)":3.5,"petal length (cm)":1.4,"petal width (cm)":0.2},{"sepal length (cm)":4.9,"sepal width (cm)":3.0,"petal length (cm)":1.4,"petal width (cm)":0.2},{"sepal length (cm)":4.7,"sepal width (cm)":3.2,"petal length (cm)":1.3,"petal width (cm)":0.2},{"sepal length (cm)":4.6,"sepal width (cm)":3.1,"petal length (cm)":1.5,"petal width (cm)":0.2},{"sepal length (cm)":5.0,"sepal width (cm)":3.6,"petal length (cm)":1.4,"petal width (cm)":0.2},{"sepal length (cm)":5.4,"sepal width (cm)":3.9,"petal length (cm)":1.7,"petal width (cm)":0.4},{"sepal length (cm)":4.6,"sepal width (cm)":3.4,"petal length (cm)":1.4,"petal width (cm)":0.3},{"sepal length (cm)":5.0,"sepal width (cm)":3.4,"petal length (cm)":1.5,"petal width (cm)":0.2},{"sepal length (cm)":4.4,"sepal width (cm)":2.9,"petal length (cm)":1.4,"petal width (cm)":0.2},{"sepal length (cm)":4.9,"sepal width (cm)":3.1,"petal length (cm)":1.5,"petal width (cm)":0.1},{"sepal l

**3. XML vers JSON**

*Q4 : écrivez le code Python qui convertit le fichier XML en code de 
langage JSON*

In [26]:
import xml.etree.ElementTree as ET
import json

xml_file = "/kaggle/input/dataset/file.xml"


tree = ET.parse(xml_file)
root = tree.getroot()


def xml_to_dict(element):
    d = {}
    for child in element:
        
        if child:
            if child.tag in d:
                if isinstance(d[child.tag], list):
                    d[child.tag].append(xml_to_dict(child))
                else:
                    d[child.tag] = [d[child.tag], xml_to_dict(child)]
            else:
                d[child.tag] = xml_to_dict(child)
        else:
            
            d[child.tag] = child.text.strip() if child.text else None
        
        if child.attrib:
            d[child.tag] = {"text": d[child.tag], "attributes": child.attrib}
    return d


xml_dict = xml_to_dict(root)


json_data = json.dumps(xml_dict, indent=4)


print(json_data)


{
    "child": {
        "text": "Exclusively",
        "attributes": {
            "name": "Frank",
            "test": "2"
        }
    },
    "unique": "Add a workbook URL here",
    "data": {
        "family": "Add the font family of your text here",
        "size": "Add the font size of your text here"
    }
}


**4. XML vers JSON**

*Q5 : écrivez le code Python qui convertit le fichier JSON 
à côté d'un code de langage XML.*

In [31]:
import json
import xml.etree.ElementTree as ET


with open('/kaggle/input/dataset/data.json') as f:
    json_data = json.load(f)


def dict_to_xml(parent, dictionary):
    for key, value in dictionary.items():
        if isinstance(value, dict):
            
            element = ET.SubElement(parent, key)
            dict_to_xml(element, value)
        elif isinstance(value, list):
            
            for item in value:
                dict_to_xml(parent, {key: item})
        else:
            
            element = ET.SubElement(parent, key)
            element.text = str(value)


root = ET.Element("root")


dict_to_xml(root, json_data)


tree = ET.ElementTree(root)

tree.write("data.xml")
